version: "3.8"
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=trackit
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trackit_backend
    ports:
      - "8089:8089"
    environment:
      - DB_SOURCE=postgresql://postgres:postgres@postgres:5432/trackit_backend?sslmode=disable
    depends_on:
      - postgres
    # entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh" ]
    # command: [ "/app/main" ]